import Sidebar from "@/components/Sidebar";
import "../styles/globals.css";

export const metadata = {
  title: "ChatGPT",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="bg-[#202123] max-w-xs h-screen overflow-y-auto md:min-w-[260px]">
          <Sidebar />
          </div>
          {/* ClientProvider - Notification */}
          <div className="bg-[#343531] flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
